### ISSUE TITLE
Error when the previous version of skeleton head is deserialized

### ISSUE THREAD

**Issue by ahnsunggwan45** [NetherGamesMC/PocketMine-MP#498] opened 2024-10-24 14:52 UTC
Thread: Main
Error: Unhandled async exception: No deserializer found for ID minecraft:skeleton_skull
File: pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await
Line: 509
Type: SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await(256): SOFe\AwaitGenerator\Await->reject(object pocketmine\data\SavedDataLoadingException#289107)
#1 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await(238): SOFe\AwaitGenerator\Await->wakeup(object Closure#289026)
#2 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await(474): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#289026)
#3 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#287512)
#4 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(174): SOFe\AwaitGenerator\AwaitChild->resolve(array[1], array[2])
#5 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlSelectResult#289115)
#6 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
#7 pmsrc/virions/libasynql/src/poggit/libasynql/base/SqlThreadPool(111): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
#8 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[1])
#9 (): [33m--- below is the original stack trace ---[m()
#10 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(223): poggit\libasynql\base\DataConnectorImpl->executeImplRaw(array[1], array[1], array[1], object Closure#281639, object Closure#289087)
#11 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(180): poggit\libasynql\base\DataConnectorImpl->executeImpl(string[7] bag.get, array[1], int 3, object Closure#281639, object Closure#289087)
#12 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(172): poggit\libasynql\base\DataConnectorImpl->executeImplLast(string[7] bag.get, array[1], int 3, object Closure#281690, object Closure#289087)
#13 plugins/Bag/src/BagDatabase(49): poggit\libasynql\base\DataConnectorImpl->executeSelect(string[7] bag.get, array[1], object Closure#334081, object Closure#289087)
#14 plugins/Bag/src/session/BagSession(68): ojy\Bag\BagDatabase->bagGet(string[8] sinh0820)
#15 (): ojy\Bag\session\BagSession->ojy\Bag\session\{closure}()
#16 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await(298): Generator->send(object Closure#289087)
#17 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await(254): SOFe\AwaitGenerator\Await->SOFe\AwaitGenerator\{closure}()
#18 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await(238): SOFe\AwaitGenerator\Await->wakeup(object Closure#205253)
#19 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/Await(474): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#205253)
#20 pmsrc/virions/await-generator/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#317513)
#21 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(174): SOFe\AwaitGenerator\AwaitChild->resolve(array[1], array[2])
#22 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlSelectResult#334079)
#23 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
#24 pmsrc/virions/libasynql/src/poggit/libasynql/base/SqlThreadPool(111): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
#25 pmsrc/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[1])
#26 pmsrc/virions/libasynql/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
#27 pmsrc/src/TimeTrackingSleeperHandler(58): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
#28 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#29 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#30 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#31 pmsrc/src/Server(1743): pocketmine\snooze\SleeperHandler->sleepUntil(float 1729781425.0081)
#32 pmsrc/src/Server(1110): pocketmine\Server->tickProcessor()
#33 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[21] /root/servers/spawn1/, string[29] /root/servers/spawn1/plugins/)
#34 pmsrc/src/PocketMine(378): pocketmine\server()

**Comment by dries-c** [comment] 2024-10-24 16:28
Which version of minecraft are you using?

**Comment by dries-c** [comment] 2024-10-25 16:09
I can't find the code of that plugin to check what's happening there.

**Comment by dries-c** [comment] 2024-10-26 14:07
Duplicate of https://github.com/NetherGamesMC/PocketMine-MP/issues/500

**Closed as completed by dries-c** 2024-10-26 14:07 UTC
