### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by StefanFox-Dev** [NetherGamesMC/PocketMine-MP#501] opened 2024-10-26 03:54 UTC
Link to crashdump: 

### Additional comments (optional)
pocketmine\data\SavedDataLoadingException: "No deserializer found for ID minecraft:piglin_head" (EXCEPTION) in "pmsrc/src/item/Item" at line 749

**Comment by dries-c** [comment] 2024-10-26 14:07
Duplicate of https://github.com/NetherGamesMC/PocketMine-MP/issues/500

**Closed as completed by dries-c** 2024-10-26 14:07 UTC
